In [1]:
# from google.colab.patches import cv2_imshow
import cv2
import numpy as np

cap = cv2.VideoCapture('E:\_amirkabir/3.mp4')  # Video input

# Define image dimensions for use in bounding boxes
frame_height, frame_width, _ = cap.read()[1].shape

# Set a noise threshold value
noise_threshold = 2000

# Read the first two frames
ret, frame1 = cap.read()
ret, frame2 = cap.read()


In [17]:
cap.read()[1].shape

(720, 1280, 3)

In [2]:
cv2.rectangle(frame2, (1, 0), (1 + 1, 0 + 1), (0, 255, 0), 2)

array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [ 46,  43,  42],
        [ 46,  43,  42],
        [ 46,  43,  42]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [ 46,  43,  42],
        [ 46,  43,  42],
        [ 46,  43,  42]],

       [[ 85,  72,  76],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [ 46,  43,  42],
        [ 46,  43,  42],
        [ 46,  43,  42]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 17,  16,  26],
        [ 17,  16,  26],
        [ 17,  16,  26]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 17,  16,  26],
        [ 17,  16,  26],
        [ 17,  16,  26]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [ 17,  16,  26],
        [ 17,  16,  26],
        [ 17,  16,  26]]

In [3]:
# 
cv2.imshow('a',frame2)


: 

In [25]:

while ret:
    # Compute the absolute difference between two consecutive frames
    frame_diff = cv2.absdiff(frame1, frame2)

    # Convert the difference to a grayscale image
    gray = cv2.cvtColor(frame_diff, cv2.COLOR_BGR2GRAY)

    # Apply image smoothing
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)

    # Detect motion and changes
    _, thresh = cv2.threshold(blurred, 20, 255, cv2.THRESH_BINARY)

    # Find bounding rectangles
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    for contour in contours:
        if cv2.contourArea(contour) > noise_threshold:
            x, y, w, h = cv2.boundingRect(contour)
            cv2.rectangle(frame2, (x, y), (x + w, y + h), (0, 255, 0), 2)

    # Display the frame with bounding boxes using cv2_imshow
    # cv2_imshow(frame2)
    cv2.imshow('a', frame2)

    # Save the current frame as the previous frame
    frame1 = frame2

    # Read the next frame
    ret, frame2 = cap.read()

cv2.destroyAllWindows()


In [ ]:
cap = cv2.VideoCapture('3.mp4')
cap

In [1]:
import cv2

camera = 'E:\_amirkabir/3.mp4' # CAM 800x600 60fps

cap = cv2.VideoCapture(camera)

while cap.isOpened():

    ret, frame = cap.read()

    if ret == True:        

        cv2.imshow('Direct', frame)            

        k = cv2.waitKey(1)

        if k%256 == 27: # ESC presse

            print("Escape, fermeture...")

            break

        framecount = 0

        capture = frame

        while True:

            framecount += 1           

            #print(framecount)

            if framecount == 600:

                _, frame1 = cap.read()

                framecount = 0

                capture1 = frame1

                break  
            

: 

In [ ]:
frame1

In [1]:
      
        # try:
        if frame.shape == frame1.shape:

            print("Les caracteristiques sont identiques")

            difference = cv2.subtract(capture, capture1)

            b, g, r = cv2.split(difference)

            b1 = cv2.resize(b, (400, 300) , interpolation = cv2.INTER_AREA)                  
            cv2.imshow('B ', b1)

            g1 = cv2.resize(g, (400, 300) , interpolation = cv2.INTER_AREA)                  
            cv2.imshow('G ', g1) 

            r1 = cv2.resize(b, (400, 300) , interpolation = cv2.INTER_AREA)                  
            cv2.imshow('R ', r1)

            print(cv2.countNonZero(b))
            print(cv2.countNonZero(g))
            print(cv2.countNonZero(r))


        if cv2.countNonZero(b) == 0 and cv2.countNonZero(g) == 0 and cv2.countNonZero(r) == 0:

            print('Les images sont identiques.')

        else:

            print('Les images sont differentes.')

            difference1 = cv2.resize(difference, (400, 300) , interpolation = cv2.INTER_AREA)       
            print(difference1)
            cv2.imshow('Difference ', difference1)  
        # except:
        #     print('')

    else:
        cap.release()
                # cv2.destroyAllWindows()

Les caracteristiques sont identiques
40060
28517
34255
Les images sont differentes.
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
Les caracteristiques sont identiques
57164
54165
48789
Les images sont differentes.
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
Les 

AttributeError: 'NoneType' object has no attribute 'shape'

: 

In [2]:
import cv2
cap = cv2.VideoCapture('E:\_amirkabir/3.mp4')  # Use 0 for the default camera or provide the path to a video file.


In [3]:
ret, frame1 = cap.read()
ret, frame2 = cap.read()

for i in range(0,5000):
    diff = cv2.absdiff(frame1, frame2)
    gray = cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5, 5), 0)
    _, thresh = cv2.threshold(blur, 20, 255, cv2.THRESH_BINARY)


In [4]:
contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)


In [5]:
for contour in contours:
    if cv2.contourArea(contour) > 1000:  # Adjust the threshold as needed
        (x, y, w, h) = cv2.boundingRect(contour)
        cv2.rectangle(frame1, (x, y), (x + w, y + h), (0, 255, 0), 2)


In [ ]:
cv2.imshow("Movement Detection", frame1)
frame1 = frame2
ret, frame2 = cap.read()

# if cv2.waitKey(40) == 27:  # Press 'Esc' key to exit
#     break

cap.release()
# cv2.destroyAllWindows()


Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "c:\Users\est\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\est\AppData\Local\Programs\Python\Python38\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "c:\Users\est\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\est\AppData\Local\Programs\Python\Python38\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data 

: 

In [1]:
import cv2
import numpy as np

# Initialize the video capture
cap = cv2.VideoCapture('E:\_amirkabir/3.mp4')  # Use 0 for the default camera

# Create a background subtractor object
fgbg = cv2.createBackgroundSubtractorMOG2()

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Apply background subtraction to the current frame
    fgmask = fgbg.apply(frame)

    # Perform morphological operations to clean up the mask
    fgmask = cv2.erode(fgmask, None, iterations=2)
    fgmask = cv2.dilate(fgmask, None, iterations=2)

    # Find contours in the mask
    contours, _ = cv2.findContours(fgmask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    for contour in contours:
        if cv2.contourArea(contour) > 6000:  # Adjust the area threshold as needed
            x, y, w, h = cv2.boundingRect(contour)
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)

    # Display the original frame with bounding boxes
    cv2.imshow("Motion Detection", frame)

    if cv2.waitKey(30) & 0xFF == 27:  # Press 'Esc' key to exit
        break

cap.release()
# cv2.destroyAllWindows()


: 

In [4]:
import cv2
import numpy as np
from pydub import AudioSegment

# Initialize the video capture
cap = cv2.VideoCapture(r'E:\_amirkabir\3.mp4')  # Use 0 for the default camera

# Create a background subtractor object
fgbg = cv2.createBackgroundSubtractorMOG2()

# Initialize a list to store frames with bounding boxes
frames_with_boxes = []

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Apply background subtraction to the current frame
    fgmask = fgbg.apply(frame)

    # Perform morphological operations to clean up the mask
    fgmask = cv2.erode(fgmask, None, iterations=2)
    fgmask = cv2.dilate(fgmask, None, iterations=2)

    # Find contours in the mask
    contours, _ = cv2.findContours(fgmask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    for contour in contours:
        if cv2.contourArea(contour) > 6000:  # Adjust the area threshold as needed
            x, y, w, h = cv2.boundingRect(contour)
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)

    # Append the frame with bounding boxes to the list
    frames_with_boxes.append(frame)

    # Display the original frame with bounding boxes
    cv2.imshow("Motion Detection", frame)

    if cv2.waitKey(30) & 0xFF == 27:  # Press 'Esc' key to exit
        break

cap.release()
cv2.destroyAllWindows()

# Save the frames with bounding boxes as a video file
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter("output.avi", fourcc, 30, (640, 480))
for frame in frames_with_boxes:
    out.write(frame)
out.release()

# Extract audio from the saved video and save it as an MP3 file
video = cv2.VideoCapture("output.avi")
fps = int(video.get(5))
audio = AudioSegment.silent(duration=0)
while True:
    ret, audio_frame = video.read()
    if not ret:
        break
    audio += AudioSegment.from_wav("temp.wav")
audio.export("output.mp3", format="avi")


In [6]:
import cv2
import numpy as np
from pydub import AudioSegment

# Initialize the video capture
cap = cv2.VideoCapture('E:\_amirkabir/3.mp4')  # Use 0 for the default camera

# Create a background subtractor object
fgbg = cv2.createBackgroundSubtractorMOG2()

# Initialize a list to store frames with bounding boxes
frames_with_boxes = []

# Get the original video dimensions and FPS
frame_width = int(cap.get(3))
frame_height = int(cap.get(4))
fps = int(cap.get(5))

# Define the codec and create a VideoWriter object with the same dimensions and FPS
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter("output.avi", fourcc, fps, (frame_width, frame_height))

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Apply background subtraction to the current frame
    fgmask = fgbg.apply(frame)

    # Perform morphological operations to clean up the mask
    fgmask = cv2.erode(fgmask, None, iterations=2)
    fgmask = cv2.dilate(fgmask, None, iterations=2)

    # Find contours in the mask
    contours, _ = cv2.findContours(fgmask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    for contour in contours:
        if cv2.contourArea(contour) > 1000:  # Adjust the area threshold as needed
            x, y, w, h = cv2.boundingRect(contour)
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)

    # Append the frame with bounding boxes to the list
    frames_with_boxes.append(frame)

    # Save the frame to the video
    out.write(frame)

    # Display the original frame with bounding boxes
    cv2.imshow("Motion Detection", frame)

    if cv2.waitKey(30) & 0xFF == 27:  # Press 'Esc' key to exit
        break

cap.release()
out.release()
cv2.destroyAllWindows()

# Extract audio from the saved video and save it as an MP3 file
audio = AudioSegment.silent(duration=0)
for frame in frames_with_boxes:
    audio += AudioSegment.from_wav("temp.wav")
audio.export("output.mp3", format="mp3")


In [ ]:
import cv2
import numpy as np

# Create a VideoCapture object to read the input video
cap = cv2.VideoCapture('E:\_amirkabir/3.mp4')

# Initialize the previous frame
previous_frame = None

# Define the codec and create a VideoWriter object to save the output video as MP4
fourcc = cv2.VideoWriter_fourcc(*'MPT4')  # Use H.264 codec for MP4 format
output_video = cv2.VideoWriter('output_video.mp4', fourcc, 30, (640, 480), isColor=True)  # Specify output file name, codec, frame rate, frame size, and color flag
p_x = 1280
p_y = 720
while True:
    ret, frame = cap.read()
    if not ret:
        break
    cnt= 1
    ksize = (5, 5)  # Size of the Gaussian filter kernel
    sigma = 1.5     # Gaussian standard deviation parameter

    # Gaussian filter
    blurred_image = cv2.GaussianBlur(frame, ksize, sigmaX=sigma)
    # Convert the frame to grayscale
    gray = cv2.cvtColor(blurred_image, cv2.COLOR_BGR2GRAY)
    

    if previous_frame is not None:
        # Calculate the absolute difference between the current frame and the previous frame
        frame_diff = cv2.absdiff(previous_frame, gray)

        # Threshold the difference image to detect motion
        motion_threshold = 128
        _, thresholded = cv2.threshold(frame_diff, motion_threshold, 255, cv2.THRESH_TOZERO_INV)

        # Find contours of the moving regions
        contours, _ = cv2.findContours(thresholded, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for contour in contours:
            x, y, w, h = cv2.boundingRect(contour)

            if (w * h < (frame.shape[0] * frame.shape[1])/12) or (w * h > (frame.shape[0] * frame.shape[1])/6) or(h > 820) or(w > 400) or((h* (3/4)) < w):
                continue
            if abs(x - p_x) > 400:
                continue
            if abs(y - p_y) > 400:
                continue
            
            
            cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
            p_x= x
            p_y= y
            p_w= w
            p_h= h
        # Write the frame with motion detection to the output video
        output_video.write(frame)

    previous_frame = gray

    cv2.imshow("Motion Detection", frame)

    if cv2.waitKey(1) & 0xFF == 27:
        break

cap.release()
output_video.release()
cv2.destroyAllWindows()
